 name: CI

on:
  push:
    branches:
      - main  # mainブランチへのプッシュ時に実行
  pull_request:
    branches:
      - main  # mainブランチへのプルリクエスト時に実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.11'  # Node.jsのバージョンを指定

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test